import type { Socket } from "socket.io";
import type { SocketCallback } from "$/types";
import type { BlobBuffer, Dataset, ScanEntry, ScanStatus } from "@/types";
import { join } from "path";
import { ArrowDown01Icon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { Server as Engine } from "@socket.io/bun-engine";
import { file, serve } from "bun";
import open from "open";
import { useCallback, useMemo, useState } from "react";
import { Server } from "socket.io";
import { toast } from "sonner";
import { execDir, publicDir } from "$/persist";
import { FRONTEND_PORT, SERVER_PORT, engine } from "$/socket";
import { TunnelManager } from "$/tunnel-manager";
import { csvToJson, isTrulyLocal } from "$/utils";
import { auth } from "$/sockets/auth";
import { history } from "$/sockets/history";
import { report } from "$/sockets/report";
import { security } from "$/sockets/security";
import { cn } from "@/lib/utils";
import { useHistoryStore } from "@/stores/history.store";
import { useProjectStore } from "@/stores/project.store";
import { useSocketStore } from "@/stores/socket.store";
import { useCallbackLock } from "@/hooks/use-callback-lock";
import { PaginationController } from "@/components/pagination";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { DropdownMenu } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Table } from "@/components/ui/table";
import index from "../dist/frontend/index.html";
